apiVersion: v1
kind: Pod
metadata:
  name: network-test-game
  labels:
    app: network-test-game
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: network-test-game
    image: docker-registry.k8s/network-test-game:BUILD_NUMBER
    resources:
      limits:
        cpu: "1.3"
      requests:
        cpu: "1.1"
    volumeMounts:
    - name: shared-data
      mountPath: /debug
    ports:
    - containerPort: 9000
    args: ["--health-check-host", "localhost", "--health-check-port", "5050"CUSTOM_OPTIONS]
    securityContext:
      privileged: true
  - name: debug
    image: docker-registry.k8s/debug:latest
    volumeMounts:
    - name: shared-data
      mountPath: /debug    
  - name: healthz
    image: docker-registry.k8s/healthz:4
    env:
      - name: VERSION
        value: "BUILD_NUMBER"
    resources:
      limits:
        cpu: "0.2"
      requests:
        cpu: "0.1"
    volumeMounts:
    - name: shared-data
      mountPath: /debug
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5

---
kind: Service
apiVersion: v1
metadata:
  name: network-test-game-service
spec:
  selector:
    app: network-test-game
  type: NodePort
  ports:
  - name: service
    protocol: UDP
    port: 9000
    nodePort: 32000
  - name: healthz
    protocol: TCP
    port: 8080
    nodePort: 32010

